#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo '------------TypeScript 💙------------'
yarn tsc --noEmit
echo '--------------ESLint 🚨--------------'
yarn lint
echo '-----------Prettier CLI ✨-----------'
yarn pretty
echo '---------------Jest 🦾---------------'
yarn test
